### ISSUE TITLE
[Bug Report] The programs keeps crashing at random

### ISSUE THREAD

**Issue by vsub** [schmaldeo/DS4Windows#52]
**Describe the bug**
Just playing games and the program just randomly crashes

**Screenshots and Logs**
All logs shows the same thing,only info catergory reports and 2 errors when it crashes

|ERROR|Thread App Crashed with message Object reference not set to an instance of an object.
|ERROR|System.NullReferenceException: Object reference not set to an instance of an object.
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Desktop (please complete the following information):**
 - Controller Make and Model: DS4 clone called Q300
 - OS: Latest Windows 10 Home
 - DS4Windows Version 3.9.7

**Comment by schmaldeo** [comment]
How often does it happen? I haven't come across this issue myself.

**Comment by vsub** [comment]
I just recently started using it but it happens once or twice a day(depends how long I use my controller)
Yesturday it happen twice and the day before that twice again with the exact same error

**Comment by schmaldeo** [comment]
Could you please use [this version](https://github.com/schmaldeo/DS4Windows/releases/tag/v3.9.1) for a day or two and see if it crashes or not?

**Comment by vsub** [comment]
Ok I will switch to it and use it for few days(during the week I don't have much free time)
And btw when I read the description of that update,I did notest something that was always working fine(I did not go back to 3.3.3 to check)
In Genshin Inpact when you want to collect things,you have to spam square\y but if you left mouse click,it will instantly collect all
When I started using your fork of DS4Windows I notest that this will not work or it will work after a delay(or maybe when I press multiple times,wondering what is going on)

**Comment by schmaldeo** [comment]
Perhaps non-zero debouncing basically disallowing very fast spam?

**Comment by vsub** [comment]
> Perhaps non-zero debouncing basically disallowing very fast spam?

Hmm when you say "very fast spam" do you think this can be related
My gamepad have a rapid fire function and I often use it
It have the ability to reduce the rapid fire rate and I usually do that

PS.No crashes yet

**Comment by schmaldeo** [comment]
Yes, if you've got debouncing a function like this basically will only function if the debouncing is off or at a value lower than the interval between signals sent by the controllers.
That is because the way debouncing is implemented is it rejects any potential faulty, bouncy input by prolonging the pressed state of the button by that amount, however it cannot differentiate between a function like that and just a bouncing switch, that is because it is potentially how a bouncing switch would behave (so basically let's say you've got a faulty switch and you press it, it sends a value of 1, then suddenly it goes to 0 and back to 1 all while you've got the button physically pressed, the function that you've described does pretty much exactly that, except in a controlled manner).
