### ISSUE TITLE
Frequent gyro related crash

### ISSUE THREAD

**Issue by stuomas** [schmaldeo/DS4Windows#57]
**Describe the bug**
Happens multiple times per ~hour. Using gyro as a mouse.

**To Reproduce**
Haven't found what specifically triggers it.

**Screenshots and Logs**
```
2024-12-22 20:01:14.8260|ERROR|Thread App Crashed with message Value was either too large or too small for an Int32.
2024-12-22 20:01:15.6363|ERROR|System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Double value)
   at DS4Windows.Mapping.CalculateControllerAngle(Int32 gyroAccelX, Int32 gyroAccelZ, DS4Device controller)
   at DS4Windows.Mapping.Scale360degreeGyroAxis(Int32 device, DS4StateExposed exposedState, ControlService ctrl)
   at DS4Windows.Mapping.MapCustom(Int32 device, DS4State cState, DS4State MappedState, DS4StateExposed eState, Mouse tp, ControlService ctrl)
   at DS4Windows.ControlService.On_Report(DS4Device device, EventArgs e, Int32 ind)
   at DS4Windows.InputDevices.DualSenseDevice.ReadInput()
```

**Desktop (please complete the following information):**
 - Dualsense, wired
 - OS: Windows 10 Pro Build 22631.4602
 - DS4Windows 3.9.8 (and at least the one release before, didn't use before that)

**Comment by schmaldeo** [comment]
Could you please check if the problem still persists in this release:
[net8.0-windows.zip](https://github.com/user-attachments/files/18319215/net8.0-windows.zip)

**Comment by stuomas** [comment]
> Could you please check if the problem still persists in this release: [net8.0-windows.zip](https://github.com/user-attachments/files/18319215/net8.0-windows.zip)

Still happens with that, same error in same function
